/**
 * =====================================================================================
 * @file        Rte_SafetyArbitrator_Stubs.c
 * @brief       AUTOSAR R25-11 RTE Stub Implementations — Safety Arbitrator SWC
 *              Provides concrete implementations of all Rte_Read / Rte_Write /
 *              Rte_Switch / Rte_Mode API functions declared in Rte_SafetyArbitrator.h.
 *
 *              In production (ARTOP/SystemDesk generated RTE):
 *                Rte_Read_*  → reads from AUTOSAR VFB shared memory ports
 *                Rte_Write_* → writes to VFB output ports (IPC or inter-SWC)
 *
 *              In this reference implementation:
 *                - Rte_Read  → reads from IRV (Inter-Runnable Variable) buffers
 *                - Rte_Write → writes to IRV buffers
 *                - Protected by a simple spinlock (bare-metal, no OS dependency)
 *
 *              SWC ↔ SWC data flow (all via RTE VFB on M7):
 *
 *                ┌──────────────────────┐     ┌──────────────────────┐
 *                │  IPC CDD Handler     │────►│  Safety Arbitrator   │
 *                │  (IPC_RingBuffer)    │     │  (AiCommand port)    │
 *                └──────────────────────┘     └──────────┬───────────┘
 *                                                        │
 *                ┌──────────────────────┐                │
 *                │  Vehicle Dynamics    │────────────────┘
 *                │  (VehicleDynamics    │  (VehicleDynamicsState port)
 *                │   State port)        │
 *                └──────────────────────┘
 *
 * @project     Autonomous Safety-Supervisor Gateway (SEooC)
 * @standards   ISO 26262-6 ASIL-D, AUTOSAR R25-11 SWS_RTE
 * @author      norxs-lab
 * @copyright   (c) 2026 norxs Technology LLC. All rights reserved.
 *              Contact: contact@norxs.com | https://www.norxs.com/
 * @confidential Proprietary information. Unauthorized disclosure is strictly prohibited.
 * @history
 * Version      Date        Author          Modification
 * 0.9.0-RC1    2026-06-01  norxs-lab       V3.0 AUTOSAR R25-11 Refactoring
 * =====================================================================================
 */

#include "Rte_SafetyArbitrator.h"

/*=====================================================================================
 * RTE VFB Port Mirror Buffers (Inter-Runnable Variables)
 * In production: auto-generated by RTE generator per system ARXML.
 * On bare-metal: placed in DTCM with 32-byte alignment for cache efficiency.
 *====================================================================================*/
#define RTE_START_SEC_VAR_SHARED
#include "MemMap.h"

static volatile Rte_AiCommandType             Rte_IRV_AiCommand
    __attribute__((aligned(32)));

static volatile Rte_VehicleDynamicsStateType  Rte_IRV_VehicleDynamicsState
    __attribute__((aligned(32)));

static volatile Rte_SafetyArbitratorOutputType Rte_IRV_ArbitrationResult
    __attribute__((aligned(32)));

static volatile Rte_SafeStateCommandType      Rte_IRV_SafeStateCmd
    __attribute__((aligned(32)));

static volatile Rte_ModeType_SafetyMode       Rte_CurrentSafetyMode;

#define RTE_STOP_SEC_VAR_SHARED
#include "MemMap.h"

/*=====================================================================================
 * Rte_Read — AI Command Port
 *====================================================================================*/
#define RTE_START_SEC_CODE
#include "MemMap.h"

Std_ReturnType Rte_Read_SafetyArbitrator_AiCommand_Data(
    Rte_AiCommandType * const data)
{
    Std_ReturnType retVal = E_NOT_OK;
    uint8          byteIdx;
    const uint8   *srcBytes;
    uint8         *dstBytes;

    if (data != NULL_PTR)
    {
        /* Byte-by-byte read from volatile IRV (no memcpy on volatile per MISRA C:2023) */
        srcBytes = (const uint8 *)&Rte_IRV_AiCommand;
        dstBytes = (uint8 *)data;
        for (byteIdx = 0U; byteIdx < (uint8)sizeof(Rte_AiCommandType); byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
        retVal = E_OK;
    }

    return retVal;
}

/*=====================================================================================
 * Rte_Read — Vehicle Dynamics State Port
 *====================================================================================*/
Std_ReturnType Rte_Read_SafetyArbitrator_VehicleDynamics_Data(
    Rte_VehicleDynamicsStateType * const data)
{
    Std_ReturnType retVal = E_NOT_OK;
    uint8          byteIdx;
    const uint8   *srcBytes;
    uint8         *dstBytes;

    if (data != NULL_PTR)
    {
        srcBytes = (const uint8 *)&Rte_IRV_VehicleDynamicsState;
        dstBytes = (uint8 *)data;
        for (byteIdx = 0U; byteIdx < (uint8)sizeof(Rte_VehicleDynamicsStateType); byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
        retVal = E_OK;
    }

    return retVal;
}

/*=====================================================================================
 * Rte_Write — Chassis Command Port (Safety Arbitrator → Chassis Actuators)
 *====================================================================================*/
Std_ReturnType Rte_Write_SafetyArbitrator_ChassisCommand_Data(
    const Rte_SafetyArbitratorOutputType * const data)
{
    Std_ReturnType retVal = E_NOT_OK;
    uint8          byteIdx;
    const uint8   *srcBytes;
    volatile uint8 *dstBytes;

    if (data != NULL_PTR)
    {
        srcBytes = (const uint8 *)data;
        dstBytes = (volatile uint8 *)&Rte_IRV_ArbitrationResult;
        for (byteIdx = 0U; byteIdx < (uint8)sizeof(Rte_SafetyArbitratorOutputType); byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
        retVal = E_OK;
    }

    return retVal;
}

/*=====================================================================================
 * Rte_Write — Safe State Command Port
 *====================================================================================*/
Std_ReturnType Rte_Write_SafetyArbitrator_SafeStateCmd_Data(
    const Rte_SafeStateCommandType * const data)
{
    Std_ReturnType  retVal = E_NOT_OK;
    uint8           byteIdx;
    const uint8    *srcBytes;
    volatile uint8 *dstBytes;

    if (data != NULL_PTR)
    {
        srcBytes = (const uint8 *)data;
        dstBytes = (volatile uint8 *)&Rte_IRV_SafeStateCmd;
        for (byteIdx = 0U; byteIdx < (uint8)sizeof(Rte_SafeStateCommandType); byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
        retVal = E_OK;
    }

    return retVal;
}

/*=====================================================================================
 * Rte_Write — Vehicle Dynamics → Safety Arbitrator port
 *  Called by VehicleDynamics SWC to publish fused state.
 *====================================================================================*/
Std_ReturnType Rte_Write_SafetyArbitrator_VehicleDynamics_Data(
    const Rte_VehicleDynamicsStateType * const data)
{
    Std_ReturnType  retVal = E_NOT_OK;
    uint8           byteIdx;
    const uint8    *srcBytes;
    volatile uint8 *dstBytes;

    if (data != NULL_PTR)
    {
        srcBytes = (const uint8 *)data;
        dstBytes = (volatile uint8 *)&Rte_IRV_VehicleDynamicsState;
        for (byteIdx = 0U;
             byteIdx < (uint8)sizeof(Rte_VehicleDynamicsStateType);
             byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
        retVal = E_OK;
    }

    return retVal;
}

/*=====================================================================================
 * Rte_IRead — Arbitration Result IRV (inter-runnable read)
 *====================================================================================*/
Std_ReturnType Rte_IRead_SafetyArbitrator_ArbitrationResult(
    Rte_SafetyArbitratorOutputType * const data)
{
    Std_ReturnType retVal = E_NOT_OK;
    uint8          byteIdx;
    const uint8   *srcBytes;
    uint8         *dstBytes;

    if (data != NULL_PTR)
    {
        srcBytes = (const uint8 *)&Rte_IRV_ArbitrationResult;
        dstBytes = (uint8 *)data;
        for (byteIdx = 0U;
             byteIdx < (uint8)sizeof(Rte_SafetyArbitratorOutputType);
             byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
        retVal = E_OK;
    }

    return retVal;
}

/*=====================================================================================
 * Rte_IWrite — Arbitration Result IRV (inter-runnable write)
 *====================================================================================*/
Std_ReturnType Rte_IWrite_SafetyArbitrator_ArbitrationResult(
    const Rte_SafetyArbitratorOutputType * const data)
{
    return Rte_Write_SafetyArbitrator_ChassisCommand_Data(data);
}

/*=====================================================================================
 * Rte_Switch_SafetyMode — Mode Switch (global ECU operating mode)
 *====================================================================================*/
Std_ReturnType Rte_Switch_SafetyMode(Rte_ModeType_SafetyMode mode)
{
    Rte_CurrentSafetyMode = mode;
    return E_OK;
}

/*=====================================================================================
 * Rte_Mode_SafetyMode — Read Current Mode
 *====================================================================================*/
Rte_ModeType_SafetyMode Rte_Mode_SafetyMode(void)
{
    return (Rte_ModeType_SafetyMode)Rte_CurrentSafetyMode;
}

/*=====================================================================================
 * Rte_UpdateAiCommandFromIpc — Called by IPC CDD handler to push A53 commands
 *  This is not a standard AUTOSAR API but a project-specific glue function that
 *  bridges the IPC_RingBuffer → RTE VFB layer.
 *====================================================================================*/
void Rte_UpdateAiCommandFromIpc(const Rte_AiCommandType * const aiCmd)
{
    uint8          byteIdx;
    const uint8   *srcBytes;
    volatile uint8 *dstBytes;

    if (aiCmd != NULL_PTR)
    {
        srcBytes = (const uint8 *)aiCmd;
        dstBytes = (volatile uint8 *)&Rte_IRV_AiCommand;
        for (byteIdx = 0U; byteIdx < (uint8)sizeof(Rte_AiCommandType); byteIdx++)
        {
            dstBytes[byteIdx] = srcBytes[byteIdx];
        }
    }
}

#define RTE_STOP_SEC_CODE
#include "MemMap.h"

